name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Create archive with selected files and directories
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          DIR="mod-sei-ia-${VERSION}"
          mkdir "$DIR"
          cp -r sei/ sip/ LICENSE README.md "$DIR/"
          tar -czf "${DIR}.tar.gz" "$DIR"
          zip -r "${DIR}.zip" "$DIR"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mod-sei-ia-*.tar.gz
            mod-sei-ia-*.zip
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
